# distromac tokyo-night: Tokyo Night Night palette
accent     = "#bb9af7"
background = "#1a1b26"
foreground = "#c0caf5"
mantle     = "#13141e"
surface0   = "#16161e"
surface1   = "#1e2030"
overlay0   = "#414868"
cursor     = "#c0caf5"
selection_foreground = "#1a1b26"
selection_background = "#c0caf5"

red     = "#f7768e"
green   = "#9ece6a"
green1  = "#73daca"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

color0  = "#15161e"
color1  = "#f7768e"
color2  = "#9ece6a"
color3  = "#e0af68"
color4  = "#7aa2f7"
color5  = "#bb9af7"
color6  = "#7dcfff"
color7  = "#a9b1d6"
color8  = "#414868"
color9  = "#f7768e"
color10 = "#9ece6a"
color11 = "#e0af68"
color12 = "#7aa2f7"
color13 = "#bb9af7"
color14 = "#7dcfff"
color15 = "#c0caf5"

bat_theme = "TwoDark"
