source "$DISTROMAC_PATH/install/helpers/logging.sh"

log_step "Post-install"

echo ""
echo "  ╔══════════════════════════════╗"
echo "  ║        d i s t r o m a c     ║"
echo "  ╚══════════════════════════════╝"
echo ""
echo "distromac installed successfully!"
echo ""
echo "Next steps:"
echo "  1. Grant Accessibility permissions to Aerospace and Sketchybar:"
echo "     System Settings → Privacy & Security → Accessibility"
echo ""
echo "  2. Set recommended Raycast hotkey for theme picker:"
echo "     Raycast → Script Commands → Pick Theme → Set Ctrl+T"
echo ""
echo "  3. Restart your terminal or run: source ~/.zshrc"
echo ""
echo "  4. Some macOS defaults may require a logout/restart."
echo ""
echo "Commands:"
echo "  distromac-theme-pick    — change theme (fzf picker)"
echo "  distromac-theme-list    — list available themes"
echo "  distromac-update        — update distromac"
echo "  distromac-version       — show version"
echo ""
