#!/usr/bin/env bash

# distromac theme integration
source "$HOME/.config/distromac/current/theme/borders"

options=(
  style=round
  width=6.0
  hidpi=on
  active_color=0xff88c0d0
  inactive_color=0xff414550
)

borders "${options[@]}"
