# distromac gruvbox: Gruvbox Dark Medium palette
accent     = "#d79921"
background = "#282828"
foreground = "#ebdbb2"
mantle     = "#1d2021"
surface0   = "#32302f"
surface1   = "#3c3836"
overlay0   = "#665c54"
cursor     = "#ebdbb2"
selection_foreground = "#282828"
selection_background = "#ebdbb2"

red     = "#cc241d"
green   = "#98971a"
green1  = "#8ec07c"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

color0  = "#282828"
color1  = "#cc241d"
color2  = "#98971a"
color3  = "#d79921"
color4  = "#458588"
color5  = "#b16286"
color6  = "#689d6a"
color7  = "#a89984"
color8  = "#928374"
color9  = "#fb4934"
color10 = "#b8bb26"
color11 = "#fabd2f"
color12 = "#83a598"
color13 = "#d3869b"
color14 = "#8ec07c"
color15 = "#ebdbb2"

bat_theme = "gruvbox-dark"
