"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "distromac"

format = """\
[λ](cyan)\
[ · ](fg_gutter)\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$jobs\
$status\
 $character"""

[line_break]
disabled = true

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[◀](bold cyan)"
vimcmd_replace_one_symbol = "[◁](bold orange)"
vimcmd_replace_symbol = "[◁](bold orange)"
vimcmd_visual_symbol = "[◀](bold blue)"

[username]
disabled = true

[hostname]
disabled = true

[directory]
format = "[$read_only]($read_only_style)[$path](bold green)[ · ](fg_gutter)"
style = "bold green"
read_only = "󰌾 "
read_only_style = "red"
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"
use_os_path_sep = true

[directory.substitutions]

[git_branch]
format = "[$branch(:$remote_branch)](blue)"
symbol = ""
style = "blue"
truncation_length = 20
truncation_symbol = "…"
only_attached = false

[git_commit]
format = '[ · ](fg_gutter)[$hash$tag](comment)'
style = "comment"
commit_hash_length = 7
tag_symbol = "󰓹"
only_detached = true
tag_disabled = false

[git_state]
format = '[ · ](fg_gutter)[$state($progress_current/$progress_total)](bold yellow)'
style = "bold yellow"
rebase = "󰳖 REB"
merge = "󰘭 MRG"
revert = "󰕌 REV"
cherry_pick = "CHR"
bisect = "BIS"
am = "AM"
am_or_rebase = "AM/R"

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'
added_style = "green"
deleted_style = "red"
disabled = false
only_nonzero_diffs = true

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "purple"
conflicted = "󰞇"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${ahead_count}↕${behind_count}"
up_to_date = ""
untracked = "?"
stashed = "󰏗"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[cmd_duration]
format = "[ · ](fg_gutter)[$duration](yellow)"
style = "yellow"
min_time = 2_000
show_milliseconds = false

[fill]
disabled = true

[jobs]
format = "[ · ](fg_gutter)[󰜎 $number](purple)"
symbol = ""
style = "purple"
number_threshold = 1
symbol_threshold = 1

[status]
format = '[ · ](fg_gutter)[✘ $status](red)'
symbol = ""
success_symbol = ""
not_executable_symbol = "󰂭"
not_found_symbol = "󰍉"
sigint_symbol = "󰂭"
signal_symbol = "󱐋"
style = "red"
map_symbol = true
recognize_signal_code = true
disabled = false

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[kubernetes]
disabled = true

[docker_context]
disabled = true

[terraform]
disabled = true

[nix_shell]
disabled = true

[conda]
disabled = true

[package]
disabled = true

[os]
disabled = true

[battery]
disabled = true

[memory_usage]
disabled = true

[shlvl]
disabled = true

[sudo]
disabled = true

[container]
disabled = true

[time]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[swift]
disabled = true

[elixir]
disabled = true

[lua]
disabled = true

[php]
disabled = true

[c]
disabled = true
