#!/usr/bin/env bash
# Auto-generated by distromac-theme-set-templates
options=(
  style=round
  width=6.0
  hidpi=on
  active_color=0xff{{ color4_strip }}
  inactive_color=0xff{{ surface1_strip }}
)
borders "${options[@]}"
