# Auto-generated by distromac-theme-set-templates
user: {{ color4 }}
group: {{ color5 }}
permission:
  read: {{ color2 }}
  write: {{ color3 }}
  exec: {{ color1 }}
  exec-sticky: {{ color1 }}
  no-access: {{ surface1 }}
  octal: {{ color6 }}
  acl: {{ color6 }}
  context: {{ color6 }}
date:
  hour-old: {{ foreground }}
  day-old: {{ color7 }}
  older: {{ surface1 }}
size:
  none: {{ surface1 }}
  small: {{ color4 }}
  medium: {{ color4 }}
  large: {{ color4 }}
inode:
  valid: {{ color4 }}
  invalid: {{ color1 }}
links:
  valid: {{ color4 }}
  invalid: {{ color1 }}
tree-edge: {{ surface1 }}
git-status:
  default: {{ surface1 }}
  unmodified: {{ surface1 }}
  ignored: {{ surface1 }}
  new-in-index: {{ color2 }}
  new-in-workdir: {{ color2 }}
  typechange: {{ color3 }}
  deleted: {{ color1 }}
  renamed: {{ color4 }}
  modified: {{ color3 }}
  conflicted: {{ color1 }}
