#!/usr/bin/env bash
# Auto-generated by distromac-theme-set-templates
# ──────────────────────────────────────────────────────────────────────────────
# Theme colors for SketchyBar (compatible with _SSDF_CM_* / _SSDF_WS_* vars)
# ──────────────────────────────────────────────────────────────────────────────

# ACCENT COLORS
export _SSDF_CM_RED=0xff{{ color1_strip }}
export _SSDF_CM_GREEN=0xff{{ color2_strip }}
export _SSDF_CM_YELLOW=0xff{{ color3_strip }}
export _SSDF_CM_BLUE=0xff{{ color4_strip }}
export _SSDF_CM_MAUVE=0xff{{ color5_strip }}
export _SSDF_CM_TEAL=0xff{{ color6_strip }}
export _SSDF_CM_LAVENDER=0xff{{ color7_strip }}
export _SSDF_CM_PINK=0xff{{ accent_strip }}
export _SSDF_CM_PEACH=0xff{{ color3_strip }}
export _SSDF_CM_SKY=0xff{{ color6_strip }}
export _SSDF_CM_SAPPHIRE=0xff{{ color4_strip }}
export _SSDF_CM_ROSEWATER=0xff{{ color15_strip }}
export _SSDF_CM_FLAMINGO=0xff{{ color15_strip }}
export _SSDF_CM_MAROON=0xff{{ color1_strip }}

# LEGACY ALIASES (backwards compatibility)
export _SSDF_CM_PURPLE=$_SSDF_CM_MAUVE
export _SSDF_CM_VIOLET=$_SSDF_CM_MAUVE
export _SSDF_CM_MAGENTA=$_SSDF_CM_PINK
export _SSDF_CM_CYAN=$_SSDF_CM_SKY
export _SSDF_CM_ORANGE=$_SSDF_CM_PEACH
export _SSDF_CM_CORAL=$_SSDF_CM_RED
export _SSDF_CM_ROSE=$_SSDF_CM_ROSEWATER
export _SSDF_CM_FROST=$_SSDF_CM_SAPPHIRE
export _SSDF_CM_MINT=$_SSDF_CM_GREEN
export _SSDF_CM_SAGE=$_SSDF_CM_GREEN
export _SSDF_CM_AQUA=$_SSDF_CM_TEAL
export _SSDF_CM_SEAFOAM=$_SSDF_CM_TEAL
export _SSDF_CM_GOLD=$_SSDF_CM_YELLOW
export _SSDF_CM_AMBER=$_SSDF_CM_YELLOW

# FOREGROUND COLORS (text hierarchy)
export _SSDF_CM_SUBTEXT_1=0xff{{ foreground_strip }}
export _SSDF_CM_SUBTEXT_0=0xff{{ color7_strip }}
export _SSDF_CM_OVERLAY_1=0xff{{ surface1_strip }}
export _SSDF_CM_OVERLAY_0=0xff{{ surface1_strip }}
export _SSDF_CM_SURFACE_2=0xff{{ surface1_strip }}
export _SSDF_CM_SURFACE_1=0xff{{ surface0_strip }}
export _SSDF_CM_SURFACE_0=0xff{{ surface0_strip }}

# BACKGROUND COLORS (depth layers)
export _SSDF_CM_MANTLE=0xdd{{ mantle_strip }}
export _SSDF_CM_MANTLE_LIGHT=0xff{{ background_strip }}
export _SSDF_CM_MANTLE_LIGHTER=0xff{{ surface0_strip }}

# WORKSPACE DOT COLORS
export _SSDF_WS_BLUE=0xff{{ color4_strip }}
export _SSDF_WS_CYAN=0xff{{ color6_strip }}
export _SSDF_WS_MAUVE=0xff{{ color5_strip }}
export _SSDF_WS_GREEN=0xff{{ color2_strip }}

# Legacy workspace aliases
export _SSDF_WS_TEAL=$_SSDF_WS_CYAN
export _SSDF_WS_PURPLE=$_SSDF_WS_MAUVE
export _SSDF_WS_MAGENTA=$_SSDF_WS_MAUVE
export _SSDF_WS_ORANGE=$_SSDF_CM_PEACH
export _SSDF_WS_ROSE=$_SSDF_CM_RED

# UTILITY
export TRANSPARENT=0x00000000
