# Auto-generated by distromac-theme-set-templates
[palettes.distromac]
# ── Background Layers ──
bg         = "{{ background }}"
bg_dark    = "{{ mantle }}"
bg_highlight = "{{ surface0 }}"
fg_gutter  = "{{ surface1 }}"
terminal_black = "{{ surface1 }}"

# ── Foreground Hierarchy ──
fg         = "{{ foreground }}"
fg_dark    = "{{ color15 }}"
comment    = "{{ color7 }}"
dark5      = "{{ surface1 }}"
dark3      = "{{ surface1 }}"

# ── Primary Blue ──
blue       = "{{ color4 }}"
blue0      = "{{ surface1 }}"
blue1      = "{{ color4 }}"

# ── Cyan ──
cyan       = "{{ color6 }}"
blue5      = "{{ color6 }}"

# ── Magenta/Purple ──
magenta    = "{{ color5 }}"
purple     = "{{ color7 }}"

# ── Green ──
green      = "{{ color2 }}"
green1     = "{{ color6 }}"
teal       = "{{ color6 }}"

# ── Warm Colors ──
orange     = "{{ color3 }}"
yellow     = "{{ color3 }}"
red        = "{{ color1 }}"
red1       = "{{ color1 }}"
