# Auto-generated by distromac-theme-set-templates

# True color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Status bar
set -g status-position top
set -g status-justify left
set -g status-style "bg={{ background }},fg={{ foreground }}"
set -g status-interval 1

# Status bar left (session name)
set -g status-left-length 40
set -g status-left "#[bg={{ color4 }},fg={{ background }},bold] #S #[bg={{ surface0 }},fg={{ color4 }}]#[bg={{ surface0 }},fg={{ foreground }}] #[bg={{ background }},fg={{ surface0 }}]"

# Status bar right
set -g status-right ""

# Window status (tabs)
set -g window-status-format "#[bg={{ mantle }},fg={{ background }}]#[bg={{ mantle }},fg={{ surface1 }}] #I #[fg={{ surface1 }}]│ #[fg={{ surface1 }}]#W #[bg={{ background }},fg={{ mantle }}]"
set -g window-status-current-format "#[bg={{ surface0 }},fg={{ background }}]#[bg={{ surface0 }},fg={{ foreground }},bold] #I #[fg={{ surface1 }}]│ #[fg={{ foreground }}]#W#[fg={{ color3 }}]#{?window_zoomed_flag, 󰊓,} #[bg={{ background }},fg={{ surface0 }}]"
set -g window-status-separator ""

# Activity monitoring
set -g window-status-activity-style "bg={{ mantle }},fg={{ color3 }}"
set -g window-status-bell-style "bg={{ mantle }},fg={{ color1 }}"

# Pane borders
set -g pane-border-style "fg={{ surface1 }}"
set -g pane-active-border-style "fg={{ color4 }}"

# Pane number display
set -g display-panes-colour "{{ surface1 }}"
set -g display-panes-active-colour "{{ color4 }}"

# Message/command mode
set -g message-style "bg={{ surface0 }},fg={{ foreground }}"
set -g message-command-style "bg={{ surface1 }},fg={{ foreground }}"

# Mode style (copy mode, etc.)
set -g mode-style "bg={{ surface1 }},fg={{ foreground }}"

# Clock mode
set -g clock-mode-colour "{{ color4 }}"
set -g clock-mode-style 24

# Copy mode highlighting
set -g copy-mode-match-style "bg={{ color3 }},fg={{ background }}"
set -g copy-mode-current-match-style "bg={{ accent }},fg={{ background }}"
set -g copy-mode-mark-style "bg={{ color6 }},fg={{ background }}"

# Popup windows
set -g popup-border-style "fg={{ surface1 }}"
set -g popup-border-lines rounded

# Menu styling
set -g menu-style "bg={{ surface0 }},fg={{ foreground }}"
set -g menu-selected-style "bg={{ surface1 }},fg={{ foreground }},bold"
set -g menu-border-style "fg={{ surface1 }}"
