# Auto-generated by distromac-theme-set-templates
# ══════════════════════════════════════════════════════════════════════════════
# Zen Minimal - tmux Theme
# Ultra-minimal status bar with dot indicators
# ══════════════════════════════════════════════════════════════════════════════

# Status bar position & general
set -g status-position bottom
set -g status-justify right
set -g status-style "bg=default,fg={{ surface1 }}"
set -g status-interval 60

# Left: empty
set -g status-left ""
set -g status-left-length 0

# Right: pipe + time in accent color
set -g status-right-length 20
set -g status-right "#[fg={{ surface0 }}]| #[fg={{ color1 }}]%H:%M"

# Active window: green dot + bright name
set -g window-status-current-format "  #[fg={{ color2 }}]● #[fg={{ foreground }}]#W"

# Inactive window: dim dot + muted name
set -g window-status-format "  #[fg={{ surface0 }}]○ #[fg={{ surface1 }}]#W"

# No separator (spacing built into format strings)
set -g window-status-separator ""

# Pane borders
set -g pane-border-style "fg={{ surface0 }}"
set -g pane-active-border-style "fg={{ color2 }}"

# Messages
set -g message-style "bg={{ background }},fg={{ foreground }}"
set -g message-command-style "bg={{ background }},fg={{ foreground }}"

# Mode (copy mode, etc.)
set -g mode-style "bg={{ surface0 }},fg={{ foreground }}"

# Clock
set -g clock-mode-colour "{{ color1 }}"
set -g clock-mode-style 24

# Popup windows
set -g popup-border-style "fg={{ surface0 }}"
set -g popup-border-lines rounded
