# Auto-generated by distromac-theme-set-templates — do not edit
# NOTE: This must be sourced AFTER zsh-syntax-highlighting

# ──────────────────────────────────────────────────────────────────────────────
# Zsh Syntax Highlighting
# ──────────────────────────────────────────────────────────────────────────────
if (( ${+ZSH_HIGHLIGHT_STYLES} )); then

    # Commands & Executables — blue
    ZSH_HIGHLIGHT_STYLES[command]='fg={{ blue }}'
    ZSH_HIGHLIGHT_STYLES[builtin]='fg={{ blue }}'
    ZSH_HIGHLIGHT_STYLES[alias]='fg={{ blue }}'
    ZSH_HIGHLIGHT_STYLES[function]='fg={{ blue }}'
    ZSH_HIGHLIGHT_STYLES[precommand]='fg={{ blue }},underline'
    ZSH_HIGHLIGHT_STYLES[hashed-command]='fg={{ blue }}'
    ZSH_HIGHLIGHT_STYLES[arg0]='fg={{ blue }}'
    ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg={{ blue }},underline'
    ZSH_HIGHLIGHT_STYLES[global-alias]='fg={{ blue }}'

    # Command substitution — cyan
    ZSH_HIGHLIGHT_STYLES[command-substitution]='fg={{ cyan }}'
    ZSH_HIGHLIGHT_STYLES[command-substitution-unquoted]='fg={{ cyan }}'
    ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg={{ cyan }}'
    ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg={{ cyan }}'

    # Options — cyan
    ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={{ cyan }}'
    ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={{ cyan }}'

    # Paths — green1 (teal-like)
    ZSH_HIGHLIGHT_STYLES[path]='fg={{ green1 }},underline'
    ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg={{ green1 }}'
    ZSH_HIGHLIGHT_STYLES[path_prefix]='fg={{ green1 }},underline'
    ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg={{ green1 }}'
    ZSH_HIGHLIGHT_STYLES[autodirectory]='fg={{ green1 }},underline'

    # Strings — green
    ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={{ green }}'
    ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={{ green }}'
    ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={{ green }}'
    ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={{ green }}'

    # Unclosed strings — red
    ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg={{ red }}'
    ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg={{ red }}'
    ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg={{ red }}'
    ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg={{ red }}'

    # Here documents — magenta
    ZSH_HIGHLIGHT_STYLES[rc-quote]='fg={{ magenta }}'

    # Variables — yellow / foreground
    ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg={{ yellow }}'
    ZSH_HIGHLIGHT_STYLES[assign]='fg={{ foreground }}'
    ZSH_HIGHLIGHT_STYLES[named-fd]='fg={{ foreground }}'
    ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg={{ foreground }}'

    # Reserved words — magenta
    ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={{ magenta }}'

    # Globbing — yellow
    ZSH_HIGHLIGHT_STYLES[globbing]='fg={{ yellow }}'
    ZSH_HIGHLIGHT_STYLES[history-expansion]='fg={{ yellow }}'

    # Operators — magenta / cyan
    ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={{ magenta }}'
    ZSH_HIGHLIGHT_STYLES[redirection]='fg={{ cyan }}'

    # Comments — overlay (muted)
    ZSH_HIGHLIGHT_STYLES[comment]='fg={{ overlay0 }},italic'

    # Errors — red
    ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={{ red }}'

    # Default
    ZSH_HIGHLIGHT_STYLES[default]='fg={{ foreground }}'
fi

# ──────────────────────────────────────────────────────────────────────────────
# Zsh Autosuggestions
# ──────────────────────────────────────────────────────────────────────────────
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg={{ overlay0 }}'

# ──────────────────────────────────────────────────────────────────────────────
# LS_COLORS / EZA_COLORS
# ──────────────────────────────────────────────────────────────────────────────
export LS_COLORS="di=38;2;{{ blue_rgb }}:ln=38;2;{{ cyan_rgb }}:so=38;2;{{ cyan_rgb }}:pi=38;2;{{ yellow_rgb }}:ex=38;2;{{ green_rgb }}:bd=38;2;{{ yellow_rgb }}:cd=38;2;{{ yellow_rgb }}:su=38;2;{{ red_rgb }}:sg=38;2;{{ red_rgb }}:tw=38;2;{{ blue_rgb }}:ow=38;2;{{ blue_rgb }}:*.tar=38;2;{{ yellow_rgb }}:*.zip=38;2;{{ yellow_rgb }}:*.gz=38;2;{{ yellow_rgb }}:*.bz2=38;2;{{ yellow_rgb }}:*.xz=38;2;{{ yellow_rgb }}:*.7z=38;2;{{ yellow_rgb }}:*.rar=38;2;{{ yellow_rgb }}"

export EZA_COLORS="di=38;2;{{ blue_rgb }}:ln=38;2;{{ cyan_rgb }}:so=38;2;{{ cyan_rgb }}:pi=38;2;{{ yellow_rgb }}:ex=38;2;{{ green_rgb }}:bd=38;2;{{ yellow_rgb }}:cd=38;2;{{ yellow_rgb }}:ur=38;2;{{ green_rgb }}:uw=38;2;{{ yellow_rgb }}:ux=38;2;{{ red_rgb }}:ue=38;2;{{ red_rgb }}:gr=38;2;{{ green_rgb }}:gw=38;2;{{ yellow_rgb }}:gx=38;2;{{ red_rgb }}:tr=38;2;{{ green_rgb }}:tw=38;2;{{ yellow_rgb }}:tx=38;2;{{ red_rgb }}:sn=38;2;{{ green1_rgb }}:sb=38;2;{{ yellow_rgb }}:da=38;2;{{ green1_rgb }}:uu=38;2;{{ blue_rgb }}:un=38;2;{{ magenta_rgb }}:gu=38;2;{{ magenta_rgb }}:gn=38;2;{{ magenta_rgb }}"
