bind R source-file ~/.config/tmux/tmux.conf

# distromac theme integration
source-file ~/.config/distromac/current/theme/tmux-theme.conf

set-environment -g PATH "$PATH:$HOME/.config/tmux/bin"

# Panes bindings
bind f resize-pane -Z
bind r command-prompt "rename-window %%"
bind s split-window -h -c "#{pane_current_path}"
bind t split-window -v -c "#{pane_current_path}"
bind n new-window -c "#{pane_current_path}"

bind w list-sessions

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-r resize-pane -R 5
bind -r C-k resize-pane -U 5

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind p run "sidecar"
bind -n C-i run "screenshot"

# Switch sessions by number (prefix + alt-N)
bind C-1 switch-client -t 1
bind C-2 switch-client -t 2
bind C-3 switch-client -t 3
bind C-4 switch-client -t 4
bind C-5 switch-client -t 5
bind C-6 switch-client -t 6
bind C-7 switch-client -t 7
bind C-8 switch-client -t 8
bind C-9 switch-client -t 9

set -g default-terminal "tmux-256color"
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^s
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 3,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 'p'

set-option -g status-style bg=default
set -g status-left-length 100

run ~/.config/tmux/plugins/tpm/tpm
